// "Compare more": a deterministic six-tile grid on every comparison page.
//
// This is ARCHITECTURE, not an override. The tiles come from a static adjacency
// list generated by scripts/seo/build-comparison-adjacency.mjs and committed to
// the repo, so the grid is identical on every render and exists for a crawler
// that fetches one page cold with an empty seo_overrides table.
//
// It is deliberately NOT the same thing as <RelatedLinks>. That block is the
// daily loop's, it is additive, it carries the heading "Keep reading" and a
// two-column card list. This one is a three-column grid of comparison tiles
// under "Compare more". If a page renders both, the URL sets are disjoint:
// anything the related-links block already shows is dropped here and refilled
// from COMPARISON_BACKFILL.

import Link from "next/link";
import { ArrowRight } from "lucide-react";
import {
  COMPARISON_ADJACENCY,
  COMPARISON_BACKFILL,
  COMPARISON_TITLES,
} from "@/lib/comparisons/adjacency.generated";
import { REDIRECTED_COMPARISON_SLUGS } from "@/lib/comparisons/redirected-slugs";
import { getSeoOverride } from "@/lib/seo/overrides";

const TILES = 6;

interface Props {
  /** Slug of the page rendering the grid, excluded from its own tiles. */
  slug: string;
  /**
   * Article body. Any /comparisons/ href already in the body is dropped from
   * the grid so a hand-written "Related comparisons" list is never repeated.
   */
  bodyHtml?: string | null;
  /** Extra hrefs this page already links near the grid. */
  exclude?: string[];
  /** Wrap in the page container. False where the parent already provides one. */
  contained?: boolean;
}

function hrefsInBody(html: string | null | undefined): string[] {
  if (!html) return [];
  return [...html.matchAll(/href=["'](\/comparisons\/[^"'#?]+)["']/g)].map((m) =>
    m[1].replace(/\/$/, ""),
  );
}

export async function CompareMore({ slug, bodyHtml, exclude, contained = true }: Props) {
  const canonical = COMPARISON_ADJACENCY[slug];
  if (!canonical?.length) return null;

  // The loop owns related_links. Never show the same URL under both headings.
  let overrideHrefs: string[] = [];
  try {
    const override = await getSeoOverride("comparisons", slug);
    overrideHrefs = (override?.related_links ?? []).map((l) => l.href.replace(/\/$/, ""));
  } catch {
    overrideHrefs = [];
  }

  const taken = new Set<string>([
    `/comparisons/${slug}`,
    ...overrideHrefs,
    ...(exclude ?? []).map((h) => h.replace(/\/$/, "")),
    ...hrefsInBody(bodyHtml),
  ]);

  const picked: string[] = [];
  for (const candidate of [...canonical, ...(COMPARISON_BACKFILL[slug] ?? [])]) {
    if (picked.length >= TILES) break;
    if (REDIRECTED_COMPARISON_SLUGS.has(candidate)) continue;
    const href = `/comparisons/${candidate}`;
    if (taken.has(href)) continue;
    taken.add(href);
    picked.push(candidate);
  }
  if (picked.length < 3) return null;

  return (
    <section
      aria-labelledby="compare-more-heading"
      data-seo-block="compare-more"
      className={
        contained
          ? "container mx-auto max-w-3xl px-4 mt-12 border-t border-border pt-8"
          : "mt-12 border-t border-border pt-8"
      }
    >
      <p className="text-[11px] uppercase tracking-wider font-semibold text-primary mb-1">
        Comparisons
      </p>
      <h2 id="compare-more-heading" className="mb-5 text-xl sm:text-2xl font-bold text-foreground">
        Compare more
      </h2>
      <ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {picked.map((s) => (
          <li key={s}>
            <Link
              href={`/comparisons/${s}`}
              className="group flex h-full flex-col justify-between gap-3 rounded-lg bg-muted/40 p-4 transition-colors hover:bg-muted"
            >
              <span className="text-sm font-semibold leading-snug text-foreground group-hover:text-primary">
                {COMPARISON_TITLES[s] ?? s}
              </span>
              <ArrowRight
                className="h-4 w-4 shrink-0 text-primary transition-transform group-hover:translate-x-0.5"
                aria-hidden="true"
              />
            </Link>
          </li>
        ))}
      </ul>
    </section>
  );
}

export default CompareMore;
